/*
 **********************************************************************************************
  * @author       : Resmi Ramakrishnan
  * @date         : 23/08/2016
  * @description  :  Utility class for Constants.
  **********************************************************************************************
*/

public without sharing class Constants 
{
    public static final String ENCODE_KEY = 'UTF-8';
    public static final String TIME_ZONE = 'America/Los_Angeles';
    public static final String LOCALE_KEY = 'en_US';
    public static final String USER_POSTFIX = '@advdev.org';

    public static final String ADMIN_PROFILE ='System Administrator';
}