/*
 **********************************************************************************************
  * @author       : Resmi Ramakrishnan
  * @date         : 23/08/2016
  * @description  :  Utility class for Constants.
  **********************************************************************************************
*/

public without sharing class Constants 
{
    public static final String ENCODE_KEY = 'UTF-8';
    public static final String TIME_ZONE = 'America/Los_Angeles';
    public static final String LOCALE_KEY = 'en_US';
    public static final String USER_POSTFIX = '@advdev.org';

    public static final String ADMIN_PROFILE ='System Administrator';
    
    public static final String NO_AUSTRALIAN_LICENSE = 'ERROR: Please upload a valid drivers license';
    public static final String NO_OPERATING_EXPENSE = 'ERROR: Please upload your total anticipated operating expenses for the event';
    public static final String NO_REVENUE_FILE = 'ERROR: Please upload your is the total anticipated revenue from your event';
    public static final String NO_BUDGET_FILE = 'ERROR: Please attach a copy of your budget showing any anticipated profit to this application';
    public static final String NO_FOOD_ACT_REGISTRATION = 'ERROR: Please select Food Act Registration';
    public static final String NO_SALL_LAYOUT = 'ERROR: Please upload a sketch or plan of your proposed stall layout*';
    public static final String NO_CURRENCY_COVERING = 'ERROR: Please upload your Certificate of Currency covering up to $20,000,000*';
    public static final String NO_FOOD_PREMISES_REGISTRATION = 'ERROR: Please upload your Certificate of Registration of Food Premises*';
    public static final String NO_FOOD_SAFETY_CERTIFICATE = 'ERROR: Please select Food Safety Supervisor Certificate';

}