public without sharing class DataFactoryForTestClass
{
/*
  **********************************************************************************************
  * @author       : Resmi Ramakrishnan
  * @date         : 23/08/2016
  * @description  : Utility class for test data creation.
  **********************************************************************************************
 
    public static Lead CreateLead()
    {
        Lead leadRecord = new Lead();
        leadRecord.LastName='TestLastName';
        leadRecord.FirstName='TestFirstName';
        leadRecord.Company='TestCompany';
        leadRecord.Status='New Application';             
        return leadRecord ;   
    }
    
   
    public static Lead createLeadForApplicationSubmission()
    {
        Lead leadRecord = new Lead();
        leadRecord.LastName='TestLastName';
        leadRecord.FirstName='TestFirstName';
        leadRecord.Company='TestCompany';
        leadRecord.Status='New Application';             
        return leadRecord ;   
    }
    
   
    public static User createUser(String lastName,Id profileId,String emailAddress)
    {
        User usr = new User(alias = lastName, email= emailAddress,
                            emailencodingkey = Constants.ENCODE_KEY, lastname = lastName,
                            timezonesidkey = Constants.TIME_ZONE,
                            languagelocalekey = Constants.LOCALE_KEY,
                            localesidkey = Constants.LOCALE_KEY, profileid = profileId,
                            username = lastName + System.currentTimeMillis() + Constants.USER_POSTFIX );
        return usr;      
    }    

*/
}