public class HttpHeaders {
	public static final String REQUEST_CONTENT_TYPE ='Content-Type';
	public static final String REQUEST_HOST = 'Host';
	public static final String REQUEST_CONTENT_LENGTH='Content-Length';
	public static final String REQUEST_CACHE_CONTROL ='Cache-Control';
	public static final String REQUEST_ACCEPT = 'Accept';
	public static final String REQUEST_ACCEPT_CHARSET = 'Accept-Charset';
	public static final String REQUEST_ACCEPT_ENCODING ='Accept-Encoding';
	public static final String REQUEST_AUTHORIZATION = 'Authorization';
	public static final String REQUEST_DATE='Date';

	public static final String RESPONSE_CONTENT_TYPE='Content-Type';
}